fn main() {
    // MSVC warns (LNK4104) that the COM exports in a cdylib should be
    // PRIVATE. The .def file is generated by rustc and cannot be annotated
    // directly, so suppress that cosmetic linker warning.
    println!("cargo:rustc-cdylib-link-arg=/IGNORE:4104");
}
